# Output directory name
output = "./output"

[input_files]
Xp_path = "./data/wo_strnum3.0_wo_ent/x_tokenised_preprocessed_pad.pkl"
vocab_path = "./data/wo_strnum3.0_wo_ent/vocab_3-11.pkl"
baseline_f = './data/wo_strnum3.0_wo_ent/baseline_f_tq-tkn.csv'

[table_prep_params]
MAX_COL_LEN = 3
MAX_ROW_LEN = 11
LENGTH_PER_CELL = 20

[model_params]
seed = 42
batch_size = 64
embedding_dim = 100
epochs = 20
otp_lr = 3e-6

[model_props]
viz_path = 'viz'
model_name = "model.pt"

[trec]
trec_path = '../trec_eval/trec_eval'
query_file_path = '../global_data/qrels.txt'
folder_name = "TREC_results"
file_name = 'LTR_k5_'
semantic_f = true
compute = true
