# Output directory name
output = "./output"

[input_files]
Xp_path = "./data/w_all_data/x_tokenised_preprocessed_pad_unk.pkl"
Xp_unpad_path = "./data/w_all_data/x_tokenised_preprocessed.pkl"
vocab_path = "./data/w_all_data/vocab_5-15_unk.pkl"
baseline_f = './data/w_all_data/baseline_f_tq-tkn.csv'

[table_prep_params]
MAX_COL_LEN = 5
MAX_ROW_LEN = 15
# LENGTH_PER_CELL = 20

[model_params]
seed = 42
batch_size = 128
embedding_dim = 100
epochs = 15
opt_lr = 3e-4

[model_props]
viz_path = 'viz'
print_every = 500

[trec]
trec_path = '../trec_eval/trec_eval'
query_file_path = '../global_data/qrels.txt'
folder_name = "TREC_results"
file_name = 'LTR_k5_'
semantic_f = true
compute = false
