
# Output directory name
output = "./output"

# Misc
CUDA_NO = 1

[input_files]
Xp_path = "./data/xp_2D_10-50.pkl"
Xn_path = "./data/xn_2D_10-50.pkl"
yp_path = "./data/yp_2D_10-50.pkl"
yn_path = "./data/yn_2D_10-50.pkl"
vocab_path = "./data/vocab_2D_10-50_complete.pkl"
baseline_f = './baseline_f_tq-tkn.csv'

[table_prep_params]
MAX_COL_LEN = 10
MAX_ROW_LEN = 50
LENGTH_PER_CELL = 20

[model_params]
seed = 42
batch_size = 64
embedding_dim = 100
epochs = 15
otp_lr = 3e-6

[model_props]
viz_path = 'viz'
model_name = "model.pt"

[trec]
trec_path = '../trec_eval/trec_eval'
query_file_path = '../global_data/qrels.txt'
folder_name = "TREC_results"
file_name = 'LTR_k5_'
semantic_f = true
